### ISSUE TITLE
gen-launchers.sh has sh-shebang but uses bash syntax

### ISSUE THREAD

**Issue by sdx23** [mlell/tapas#4]
gen-launchers.sh may fail when used in systems for which /usr/bin/sh is dash and not bash. The function statement (e.g. line 47) seems not to be supported.

**Comment by mlell** [comment]
Yep, we found out at the same time ;-)   Fixed in https://github.com/mlell/tapas/commit/eacfcfecb4576092b91d7922e7eda08ff41359e8
