### ISSUE TITLE
Read simulation and parameter testing for PE reads?

### ISSUE THREAD

**Issue by hans-vg** [mlell/tapas#8]
I ran through the tutorial and was able to process until the last performance metric step.  However, I would like to tune parameters for PE data, not SE data. How could I generate a PE dataset?  

Thank you.

**Comment by mlell** [comment]
Hello, @hans-vg! Sampling paired-end reads from a given reference is not implemented here. You would need to program your own solution that does this. If you generate a FASTQ file with the sampled reads it can be treated in the same way as a FASTQ file generated by TAPAS tools.
